name: Linux Alt (pipenv)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Qt and Xcb dependencies
      run: |
        # Need dependencies to work
        # https://github.com/ActivityWatch/activitywatch/pull/604
        # Big thanks for documenting your steps and problem
        sudo apt-get update
        sudo apt-get install -y qt5-default libfontconfig1 libxcb1
    - name: Install and configure pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev
    - name: Build with pyinstaller
      run: |
        pipenv run pyinstaller app.py -n omnic_rewards_Linux --onefile
    - name: Export executable build file
      uses: actions/upload-artifact@v2.2.4
      with:
        name: linux-build
        path: dist/
