# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows Build Executable

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and configure pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev
    - name: Build with pyinstaller
      run: |
        pyinstaller gui.py -n omnic_rewards_Windows -w -i icons\iconowl.ico --onefile 
    - name: Export .exe build file
      uses: actions/upload-artifact@v2.2.4
      with:
        name: windows-build
        path: dist/omnic_rewards_Windows.exe
